### PR TITLE
Restart logic

### PR DESCRIPTION
**Pull request by Gurveer90**

### CODE REVIEW

**Comment by luvaria** [comment]
This won't necessarily work if other levels are added since some might end up with the same 'length'. If we're going to add an Undo function anyway, maybe Restart could work off of that instead? (Remember a list of previous States as the level is played--Restart reverts to the first State in that list)

**Comment by jsondoo** [comment]
Yea, although this will work given our current levels, it won't work when distinct boards end up having the same 'length'. 

Maybe we could pass around the level we are playing in addition to the state. Or what rebecca suggested is a good idea too 👍

**Comment by Gurveer90** [comment]
Yes, I know this is not work for distinct board with same length. To
implement undo we need to pass previous level while calling play or
getnextboard.

**Comment by Gurveer90** [comment]
sending new request

**Pull request closed without merging**
